def CONJUGAISONS_VERBE_1ER_GROUP(RADICAL_DU_VERBE,VERBE):
#CONJUGAISONS DES VERBES DU 1ER GROUPE SE TERMINANT PAR ER
	RADICAL_DU_VERBE = VERBE[:-1]
	print("VERBE DU PREMIER GROUPE")
	print(f"\tJE			{RADICAL_DU_VERBE}RAI"
		f"\n\tTU   			{RADICAL_DU_VERBE}RA"
		f"\n\tIL / ELLES 		{RADICAL_DU_VERBE}RA"
		f"\n\tNOUS 			{RADICAL_DU_VERBE}RONS"
		f"\n\tVOUS 			{RADICAL_DU_VERBE}REZ"
		f"\n\tILS / ELLES 		{RADICAL_DU_VERBE}RONT")

def CONJUGAISONS_VERBE_2EME_GROUP(RADICAL_DU_VERBE,VERBE):
#CONJUGAISONS DES VERBES DU 2EME GROUPE SE TERMINANT PAR IR
	RADICAL_DU_VERBE = VERBE[:-1]
	print("VERBE DU DEUXIEME GROUPE")
	print(f"\tJE			{RADICAL_DU_VERBE}RAI"
		f"\n\tTU			{RADICAL_DU_VERBE}RA"
		f"\n\tIL / ELLES		{RADICAL_DU_VERBE}RA"
		f"\n\tNOUS 			{RADICAL_DU_VERBE}RONS"
		f"\n\tVOUS 			{RADICAL_DU_VERBE}REZ"
		f"\n\tILS / ELLES		{RADICAL_DU_VERBE}RONT")

def CONJUGAISONS_VERBE_3EME_GROUP(RADICAL_DU_VERBE,VERBE):
	#CONJUGAISONS DES VERBES DU 3EME GROUPE SE TERMINANT PAR RE
	RADICAL_DU_VERBE = VERBE[:-2]
	print("VERBE DU TROIXIEME GROUPE")
	print(f"\tJE   		  	{RADICAL_DU_VERBE}RAI"
		f"\n\tTU   			{RADICAL_DU_VERBE}RA"
		f"\n\tIL / ELLE 		{RADICAL_DU_VERBE}RA"
		f"\n\tNOUS 			{RADICAL_DU_VERBE}RONS"
		f"\n\tVOUS 			{RADICAL_DU_VERBE}REZ"
		f"\n\tILS / ELLES 		{RADICAL_DU_VERBE}RONT")

def CONJUGAISONS_VERBE_PEUT_DIFFERENT(VERBE):
	#VERBE ALLER AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	if VERBE == "ALLER":
		print("VERBE DU TROIXIEME GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR ER \n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJ'	IRAI"
			"\n\tTU 	IRAS"
			"\n\tIL 	IRA"
			"\n\tNOUS 	IRONS"
			"\n\tVOUS 	IREZ"
			"\n\tILS 	IRONT")

	#VERBE BOIRE AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	elif VERBE == "BOIRE":
		print("VERBE DU TROIXIEME GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR RE\n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJE 	BUVRAI"
			"\n\tTU 	BUVRAS"
			"\n\tIL 	BUVRA"
			"\n\tNOUS 	BUVRONS"
			"\n\tVOUS 	BUVREZ"
			"\n\tILS 	BUVRONT")

	#VERBE VOIRE AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	elif VERBE == "VOIR":
		print("VERBE DU TROIXIEME GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR RE\n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJE 	VERRAI"
			"\n\tTU 	VERRAS"
			"\n\tIL 	VERRA"
			"\n\tNOUS	VERRONS"
			"\n\tVOUS	VERREZ"
			"\n\tILS 	VERRONT")

	#VERBE VENIR AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	elif VERBE == "VENIR":
		print("VERBE DU TROIXIEME GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR RE\n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJE 	VIENDRAI"
			"\n\tTU 	VIENDRA"
			"\n\tIL 	VIENDRA"
			"\n\tNOUS	VIENDRONS"
			"\n\tVOUS	VIENDREZ"
			"\n\tILS 	VIENDRONT")

	#VERBE DEVOIR AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	elif VERBE == "DEVOIR":
		print("VERBE DU TROIXIEME GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR RE\n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJE 	DEVRAI"
			"\n\tTU 	DEVRAS"
			"\n\tIL 	DEVRA"
			"\n\tNOUS	DEVRONS"
			"\n\tVOUS	DEVREZ"
			"\n\tILS 	DEVRONT")
