def CONJUGAISONS_VERBE_1ER_GROUP(RADICAL_DU_VERBE,VERBE):
#CONJUGAISONS DES VERBES DU 1ER GROUPE SE TERMINANT PAR ER
	RADICAL_DU_VERBE = VERBE[:-2]
	print("VERBE DU PREMIER GROUPE")
	print(f"\tJE 			{RADICAL_DU_VERBE}AIS"
		f"\n\tTU 			{RADICAL_DU_VERBE}AIS"
		f"\n\tIL / ELLE 		{RADICAL_DU_VERBE}AIT"
		f"\n\tNOUS 			{RADICAL_DU_VERBE}IONS"
		f"\n\tVOUS 			{RADICAL_DU_VERBE}IEZ"			
		f"\n\tILS / ELLES 		{RADICAL_DU_VERBE}AIENT")


def CONJUGAISONS_VERBE_2EME_GROUP(RADICAL_DU_VERBE,VERBE):
	#CONJUGAISONS DES VERBES DU 2EME GROUPE SE TERMINANT PAR IR
		RADICAL_DU_VERBE = VERBE[:-1]
		print("VERBE DU DEUXIEME GROUPE")
		print(f"\tJE 		{RADICAL_DU_VERBE}SSAIS"
			f"\n\tTU 		{RADICAL_DU_VERBE}SSAIS"
			f"\n\tIL / ELLE 	{RADICAL_DU_VERBE}SSAIT"
			f"\n\tNOUS 		{RADICAL_DU_VERBE}SSIONS"
			f"\n\tVOUS 		{RADICAL_DU_VERBE}SSIEZ"
			f"\n\tILS / ELLES 	{RADICAL_DU_VERBE}SSAIENT")

def CONJUGAISONS_VERBE_3EME_GROUP(RADICAL_DU_VERBE,VERBE):
	#CONJUGAISONS DES VERBES DU 3EME GROUPE SE TERMINANT PAR RE
		RADICAL_DU_VERBE = VERBE[:-2]
		print("VERBE DU DEUXIEME GROUPE")
		print(f"\tJE 		{RADICAL_DU_VERBE}AI"
			f"\n\tTU 		{RADICAL_DU_VERBE}RA"
			f"\n\tIL / ELLE 	{RADICAL_DU_VERBE}RA"
			f"\n\tNOUS 		{RADICAL_DU_VERBE}RONS"
			f"\n\tVOUS 		{RADICAL_DU_VERBE}REZ"
			f"\n\tILS / ELLES 	{RADICAL_DU_VERBE}RONT")

def CONJUGAISONS_VERBE_PEUT_DIFFERENT(VERBE):
#VERBE MANGER  AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	if VERBE == "MANGER":
		print("VERBE DU PREMIER GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR ER \n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJE 	MANGEAIS"
			"\n\tTU 	MANGEAIS"
			"\n\tILS 	MANGEAIT"
			"\n\tNOUS 	MANGIONS"
			"\n\tVOUS 	MANGIEZ"
			"\n\tILS 	MANGEAIENT")

#VERBE PRENDRE AVEC UNE CONJUGAISONS PEUT DIFFERENTE
	if VERBE == "PRENDRE":
		print("VERBE DU TROIXIEME GROUPE")
		print(f"IL SAGIT D'UN VERBE ASSEZ PARTICULIER , {VERBE} EST UN VERBE SE TERMINANT PAR RE \n"
			"SA CONJUGAISONS SE FAIT COMME SUIS :"
			"\n\tJE 	PRENNAIS"
			"\n\tTU 	PRENNAIS"
			"\n\tILS 	PRENNAIT"
			"\n\tNOUS 	PRENNIONS"
			"\n\tVOUS 	PRENNIEZ"
			"\n\tILS 	PRENNAIENT")
